import type { Metadata } from "next";
import "./globals.css";

import { NavBarMobile } from "@/components/Navigation";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="font-serif">
        <NavBarMobile />
        {children}
        <Footer />
      </body>
    </html>
  );
}
